baseURL = "/"
languageCode = "en-us"
title = "LandMarkdown"
theme = "kube"
description = "Geospatial Analytics and Applications project by G1T7"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "LandMarkdown (G1T7)" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = ""

[[menu.main]]
    name = "Proposal"
    weight = 1
    url = "/proposal/"
[[menu.main]]
    name = "Research Paper"
    weight = 2
    url = "/researchpaper/"
[[menu.main]]
    name = "Poster"
    weight = 3
    url = "/poster/"
[[menu.main]]
    name = "Application"
    weight = 4
    url = "https://landmarkdown.shinyapps.io/application/"
