---
description: What is this project about and who are the project team members?
draft: FALSE
title: About
---

## What is this project about?

LandMarkdown is a project that focuses on the role geospatial analytics can play in real-world situations. In this project, the LandMarkdown project team members apply the geospatial analysis techniques, such as spatial point pattern analysis and spatial autocorrelation, on businesses registered on [Accounting and Corporate Regulatory Authority (ACRA)](https://www.acra.gov.sg/) in Singapore. The analyses will be performed using the R programming language, and some R packages will also be used for this project.

In addition, we will be publishing an R Shiny application so that users are able to visualise the results of the analyses , and also to observe the differences in the analysis by tweaking certain parameters by themselves.

## Who are the project team members?

We consist of 3 students from [Singapore Management University (SMU)](https://www.smu.edu.sg/) who are currently taking IS415 - Geospatial Analytics and Applications.

### Cheong Wei Herng, Eugene

A third-year undergraduate student from SMU studying for a Bachelor of Science in Information Systems, with majors in Business Analytics and Digital Business Solutioning. An avid player of Taiwanese-style mahjong.

### Choy Jing Wei

A third-year undergraduate student from SMU studying for a Bachelor of Science in Information Systems majoring in Business Analytics.

### Kang Yi Qi

A year 4 undergraduate student who is pursing Information Systems with Software Development and Business Analytics in Singapore Management University. Plays competitive bowling in SMU Bowling Club on her free time.

## Who is the project sponsor?

### Professor Kam Tin Seong

The project sponsor for this SMU-X module is [Professor Kam Tin Seong](https://www.smu.edu.sg/faculty/profile/9618/KAM-Tin-Seong), an Associate Professor of Information Systems (Practice). He is also the faculty member teaching IS415 - Geospatial Analytics and Applications in Singapore Management University for the Academic Year 2020-21 Semester 1.
